Graphql error and encoding error with current setup
With the latest graphql version 16, it throws graphql error `Cannot find module 'graphql/validation/rules/UniqueTypeNames'` 
By installing `graphql@15.5.3` this error is fixed

And in my system (may be it has to do with windows or something else but others might have the same system or setup like me) it throws error: 
`(node:9500) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Cannot parse the unexpected character "\uFFFD".`
which is fixed when adding `{ encoding: "utf16le"}` as 2nd argument to `readFileSync` function