Treat GraphQLRequestContext.overallCachePolicy as optional
This got changed in apollographql/apollo-server#5248 but the code using it calls out we need to maintain compatibility with Apollo Server https://github.com/apollographql/federation/blob/d900859c766645cd617eb865864d326c0431a380/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L116-L124

This fixes the following Typescript validation error:

```
gateway-js/src/datasources/RemoteGraphQLDataSource.ts:122:7 - error TS2774: This condition will always return true since this function is always defined. Did you mean to call it instead?

122       options.incomingRequestContext.overallCachePolicy?.restrict
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It _seems_ like we should've run into this previously, since this the ternary version of this check was fixed in TS 3.9.0 according to microsoft/TypeScript/#36048